# Generated by Django 2.0 on 2023-07-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Task',
            new_name='data',
        ),
    ]
