# Generated by Django 2.0 on 2023-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230713_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Completetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Deletetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
