# Generated by Django 2.0 on 2023-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230713_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Entryno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
