# Generated by Django 2.0 on 2023-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230713_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Taskno',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
