# Generated by Django 2.0 on 2023-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_todo_taskno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Taskno',
        ),
    ]
