# Generated by Django 2.0 on 2023-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_todo_taskno'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Taskno',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
