# Generated by Django 2.0 on 2023-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_todo_taskno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Entryno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
