# Generated by Django 2.0 on 2023-07-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230713_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='CompleteTask',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='DeleteTask',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='UpdateTask',
        ),
    ]
