# Generated by Django 2.0 on 2023-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230713_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='CompleteTask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='DeleteTask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='UpdateTask',
            field=models.BooleanField(default=False),
        ),
    ]
