# Generated by Django 2.0 on 2023-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20230713_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='taskno',
            field=models.IntegerField(default=1),
        ),
    ]
