# Generated by Django 2.0 on 2023-07-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230713_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskno',
            field=models.IntegerField(default=1),
        ),
    ]
