# Generated by Django 2.0 on 2023-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20230714_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
