# Generated by Django 2.0 on 2023-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230714_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskno',
            field=models.CharField(blank=True, default=1, max_length=5, null=True),
        ),
    ]
