# Generated by Django 2.0 on 2023-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20230714_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='taskno',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
